
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 27 20:43:08 COT 2021
//----------------------------------------------------

package SoloLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 38;
  public static final int Coma = 51;
  public static final int Llave_c = 45;
  public static final int Op_booleano = 41;
  public static final int Double = 12;
  public static final int Llave_a = 44;
  public static final int Unsigned = 17;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Default = 23;
  public static final int Else = 7;
  public static final int Cout = 56;
  public static final int Enum = 24;
  public static final int Break = 18;
  public static final int Corchete_c = 47;
  public static final int Corchete_a = 46;
  public static final int Extern = 25;
  public static final int Union = 29;
  public static final int Long = 20;
  public static final int Punto = 50;
  public static final int Parent_c = 43;
  public static final int Parent_a = 42;
  public static final int Return = 28;
  public static final int While = 9;
  public static final int Division = 36;
  public static final int Int = 11;
  public static final int Cadena = 5;
  public static final int Float = 13;
  public static final int For = 10;
  public static final int P_coma = 49;
  public static final int EOF = 0;
  public static final int Printf = 53;
  public static final int error = 1;
  public static final int Switch = 30;
  public static final int Linea = 2;
  public static final int Char = 14;
  public static final int Op_atribucion = 39;
  public static final int ERROR = 58;
  public static final int Do = 8;
  public static final int Continue = 22;
  public static final int Op_logico = 37;
  public static final int Case = 19;
  public static final int Short = 16;
  public static final int Register = 27;
  public static final int GoTo = 26;
  public static final int Scanf = 54;
  public static final int Const = 15;
  public static final int Identificador = 52;
  public static final int Cin = 55;
  public static final int Struct = 21;
  public static final int Resta = 34;
  public static final int Typedef = 31;
  public static final int Multiplicacion = 35;
  public static final int Op_incremento = 40;
  public static final int Numero = 57;
  public static final int Suma = 33;
  public static final int Main = 48;
  public static final int Igual = 32;
  public static final int Comillas = 3;
}

